-- ============================================================
-- Bloom & Brew — Inventory & Consumption Schema
-- SQLite dialect (also portable to Postgres/MySQL with minor tweaks)
-- ============================================================

PRAGMA foreign_keys = ON;

-- ------------------------------------------------------------
-- 1. PRODUCTS
-- Master list of ingredients / stock-keeping units (not menu
-- items — e.g. "Arabica Coffee Beans", not "Latte").
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    product_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    sku                TEXT NOT NULL UNIQUE,
    name               TEXT NOT NULL,
    category           TEXT NOT NULL,             -- e.g. 'coffee_bean','dairy','bakery','packaging'
    unit               TEXT NOT NULL,              -- 'g','kg','ml','l','pcs'
    reorder_point      REAL NOT NULL DEFAULT 0,    -- stock level that triggers a reorder
    reorder_qty        REAL NOT NULL DEFAULT 0,    -- suggested quantity to reorder
    lead_time_days     INTEGER NOT NULL DEFAULT 2, -- supplier lead time
    default_shelf_life_days INTEGER NOT NULL DEFAULT 7,
    is_active          INTEGER NOT NULL DEFAULT 1,
    created_at         TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ------------------------------------------------------------
-- 2. BATCHES
-- Every delivery/lot received. Enables FIFO tracking and
-- batch-level shelf-life / expiry monitoring.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS batches (
    batch_id           INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id         INTEGER NOT NULL REFERENCES products(product_id),
    batch_code         TEXT NOT NULL,
    supplier           TEXT,
    quantity_received  REAL NOT NULL,
    quantity_remaining REAL NOT NULL,
    unit_cost          REAL NOT NULL DEFAULT 0,
    received_at        TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at         TEXT NOT NULL,               -- received_at + shelf life
    status             TEXT NOT NULL DEFAULT 'ACTIVE' -- ACTIVE, DEPLETED, EXPIRED, DISCARDED
        CHECK (status IN ('ACTIVE','DEPLETED','EXPIRED','DISCARDED')),
    UNIQUE(product_id, batch_code)
);

CREATE INDEX IF NOT EXISTS idx_batches_product ON batches(product_id);
CREATE INDEX IF NOT EXISTS idx_batches_expiry  ON batches(expires_at);

-- ------------------------------------------------------------
-- 3. CONSUMPTION LOG
-- Every unit consumed — a sale, waste, spoilage, or sample —
-- tied to a specific batch so patterns and FIFO can be derived.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consumption_log (
    consumption_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id         INTEGER NOT NULL REFERENCES products(product_id),
    batch_id           INTEGER REFERENCES batches(batch_id),
    quantity_used      REAL NOT NULL,
    reason             TEXT NOT NULL DEFAULT 'sale'  -- 'sale','waste','spoilage','sample','adjustment'
        CHECK (reason IN ('sale','waste','spoilage','sample','adjustment')),
    order_ref          TEXT,                          -- links back to a POS order number, if applicable
    used_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_consumption_product_time ON consumption_log(product_id, used_at);
CREATE INDEX IF NOT EXISTS idx_consumption_batch ON consumption_log(batch_id);

-- ------------------------------------------------------------
-- 4. RESTOCK ALERTS
-- Generated by the backend simulation — a running log of
-- low-stock, projected-stockout, and expiring-batch warnings.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS restock_alerts (
    alert_id           INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id         INTEGER NOT NULL REFERENCES products(product_id),
    batch_id           INTEGER REFERENCES batches(batch_id),   -- set for EXPIRING_SOON alerts
    alert_type         TEXT NOT NULL
        CHECK (alert_type IN ('LOW_STOCK','STOCKOUT_PROJECTED','EXPIRING_SOON')),
    severity           TEXT NOT NULL DEFAULT 'MEDIUM'
        CHECK (severity IN ('LOW','MEDIUM','HIGH')),
    message            TEXT NOT NULL,
    suggested_qty      REAL,
    created_at         TEXT NOT NULL DEFAULT (datetime('now')),
    resolved           INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_alerts_unresolved ON restock_alerts(product_id, alert_type, resolved);
